import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[ env ]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[window]
decorations = "None"
dynamic_padding = false

[window.padding]
x = 25
y = 20
